repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

- repo: local
  hooks:
  - id: autopep8
    name: autopep8
    entry: autopep8
    language: system
    types: [python]
    args: [--in-place, --aggressive, --aggressive, src/*]

  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
    args: [src/*]