stages:
  prepare:
    cmd: python src/data/process_data.py process
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/process_data.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
    - data/processed/test.json

  train:
    cmd: python src/models/process_model.py process
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/process_model.py
    outs:
    - models/XGBModel.dat
