name: Main

on: [push]

jobs:
  autoflake-stage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: autoflake install
          run: pip install autoflake
        - name: autoflake fix
          run: autoflake --in-place src/*
  lint-stage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: flake8 install
          run: pip install flake8
        - name: flake8 check
          run: flake8 src/*
  doc-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: sphinx install
        run: pip install sphinx
      - name: gen docs
        run: cd docs && make html
